Added first version of expressor (is yet to be properly checked and/o…
ruca905/GeometryCore pull request #25
Opened 2021-09-07 22:14 UTC by Dirakon

…r used)

2021-09-08 19:44 UTC, ruca905 requested changes

2021-09-08 19:44 UTC, ruca905 commented on src/test/java/ExpertSystemTest.java
> +    public void ExpressorTest() {
There have to be it's own test file for each file in project

2021-09-08 19:44 UTC, ruca905 commented on src/test/java/ExpertSystemTest.java
> +        assertTrue(!(answerAC instanceof RaisedInThePower) && ! (answerAC instanceof Polynomial));
Hmm, i think you should fully check what is in subobjects, there is 2 RaisedInThePower object instead of one((...)^(-1) * (...)^(-1)) in for me debugger. It is good to make special function for this, which also will help us in ExpertSystem algorithm (issue #27)

2021-09-08 19:44 UTC, ruca905 commented on src/main/java/GeometryCore/AlgebraProcessor.java
> +            //This is a monomial with variable, so we leave it where it is
Very often comment is not a good way to explain code, because when code be change, comments will point on null space

2021-09-08 19:53 UTC, Dirakon commented on src/main/java/GeometryCore/AlgebraProcessor.java
> +            //This is a monomial with variable, so we leave it where it is
Overuse of comments is a bad thing, but I don't think that I overuse them

2021-09-09 09:50 UTC, ruca905 requested changes

2021-09-09 09:50 UTC, ruca905 commented on src/main/java/GeometryCore/AlgebraProcessor.java
> +public class AlgebraProcessor {
When i was planned this class, i thought that it will be several small public methods, which will create comfort utility class for management with expressions. It turned out, that just code for express variable is about 180 lines of code and many private methods. It is unreal to maintain such code. Now, you should to determine each problem, which you code solve and put it in different classes without static context(i even think that it is better to make their all lazy). Also you have to make tests for all these classes.

2021-09-09 09:50 UTC, ruca905 commented on src/main/java/GeometryCore/AlgebraProcessor.java
> +    private static boolean tryFindVariableAndPutItInHashSet(NumberValue variable, Monomial equation, HashSet<Monomial> whereToPut) {
For example, it is not directly problem of expression variable class

2021-09-09 09:50 UTC, ruca905 commented on src/main/java/GeometryCore/AlgebraProcessor.java
> +            //This is a monomial with variable, so we leave it where it is
But all functions must encapsulate implementation and user don't have to write it to understand how to use this function. Hence it is useless, when we write any comments in the function body.

2021-09-09 09:50 UTC, ruca905 commented on src/main/java/GeometryCore/GeometryObjects/Monomial.java
> +    public String getUniqueStructureString(){
There is also should be separate class, which provide opportunity to compare 2 monomials. And this class must be covered of tests also.

2021-09-09 09:50 UTC, ruca905 commented on src/test/java/AlgebraProcessorTest.java
> +        final String expectedStructureAB = "class GeometryCore.GeometryObjects.RaisedInThePower[class GeometryCore.GeometryObjects.Polynomial[class GeometryCore.GeometryObjects.RaisedInThePower[class
Hmm, it is strange way to cast it to strings. May be do it without casts. And also, as i understood, it compares only by signature and does not see which line segments there are, for example.

2021-09-14 20:04 UTC, merged